### ISSUE TITLE
Pending ToDo Items

### ISSUE THREAD

**Issue by rajdhandus** [rajdhandus/teachhub#29]
- [ ] Sort by rating count
- [ ] Clean up database
- [ ] Session restriction
- [ ] Sign-out link on all pages
- [ ] Normalize gradeLevel, subject, name, etc
